### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by simsimler** [chorokdev/chorok-rewrite#4]

**Comment by simsimler** [comment]
¡DEA: 알겠습니다
On 2021-10-30T06:29:16.586000+00:00

## Attachments

**Comment by simsimler** [comment]
2490: **버그 제보 방식이 변경됩니다**
버그 제보 시 <https://github.com/chorokdev/chorok-rewrite/issues/4> 이슈에 자동으로 코맨트가 등록됩니다. 따라서 **버그 제보** 그 자체만 해주시기 바랍니다.

**아래와 같은 메시지들은 허용하지 않습니다**
초록이 작동하지 않아요 ㅜㅜ (X)(이런 내용은 <#773105523682705430> 채널에서 이야기해주시면 처리하겠습니다!)

재생을 하려고 했는데 ValueError가 발생해요(X)(오류를 스크린샷으로 따로 첨부해주시기 바랍니다!)

이런 오류가 발생하면서 안되네요 ㅜㅜ(전송)<오류 스크린샷>(전송)(X)(한번에 전부 다 전송해주시기 바랍니다!)
On 2021-10-31T10:40:07.070000+00:00

## Attachments

**Comment by simsimler** [comment]
광민: 알 수 없는 오류가 발생했습니다.
오류가 계속 발생할 경우 서포트 서버의 버그 채널에 문의하시기 바랍니다.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/client.py", line 186, in handle_command
    await target.invoke(interaction, options)
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/command.py", line 64, in invoke
    return await self.coro(*args, **options)
  File "/app/addons/music.py", line 144, in _play
    vc = await self.connect_voice(
  File "/app/addons/music.py", line 79, in connect_voice
    vc = await self.bot.audio.connect(guild_id, voice_channel)
  File "/app/utils/discodo.py", line 188, in connect
    raise NodeNotConnected
discodo.errors.NodeNotConnected
On 2021-11-02T09:50:42.492000+00:00

## Attachments

**Comment by simsimler** [comment]
상대: 
On 2021-11-02T09:53:42.688000+00:00

## Attachments
content_type: image/png
filename: unknown.png
height: 408
id: 905031910986747934
proxy_url: https://media.discordapp.net/attachments/773110691624124486/905031910986747934/unknown.png
size: 42815
url: https://cdn.discordapp.com/attachments/773110691624124486/905031910986747934/unknown.png
width: 582

**Comment by simsimler** [comment]
상대: 알 수 없는 오류가 발생했습니다.
오류가 계속 발생할 경우 서포트 서버의 버그 채널에 문의하시기 바랍니다.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/client.py", line 186, in handle_command
    await target.invoke(interaction, options)
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/command.py", line 64, in invoke
    return await self.coro(*args, **options)
  File "/app/addons/music.py", line 144, in _play
    vc = await self.connect_voice(
  File "/app/addons/music.py", line 79, in connect_voice
    vc = await self.bot.audio.connect(guild_id, voice_channel)
  File "/app/utils/discodo.py", line 188, in connect
    raise NodeNotConnected
discodo.errors.NodeNotConnected
On 2021-11-02T09:54:30.699000+00:00

## Attachments

**Comment by simsimler** [comment]
𝗠.赤月 ×͜×[ 𝒥 ] ❛ 사 탄 ❜🍒: 왜그런지 알수있을까요
On 2021-11-03T01:11:44.038000+00:00

## Attachments

**Comment by simsimler** [comment]
𝗠.赤月 ×͜×[ 𝒥 ] ❛ 사 탄 ❜🍒: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/client.py", line 186, in handle_command
    await target.invoke(interaction, options)
  File "/usr/local/lib/python3.9/site-packages/dico_interaction/command.py", line 64, in invoke
    return await self.coro(*args, **options)
  File "/app/addons/music.py", line 349, in _stop
    await self.bot.audio.get_vc(ctx.guild_id).destroy()
  File "/app/utils/discodo.py", line 162, in get_vc
    raise VoiceClientNotFound
discodo.errors.VoiceClientNotFound
On 2021-11-03T01:11:35.847000+00:00

## Attachments

**Comment by simsimler** [comment]
alstj: 오류가 발생하네요
On 2021-11-03T02:11:20.096000+00:00

## Attachments
content_type: image/png
filename: unknown.png
height: 445
id: 905277937744486420
proxy_url: https://media.discordapp.net/attachments/773110691624124486/905277937744486420/unknown.png
size: 43372
url: https://cdn.discordapp.com/attachments/773110691624124486/905277937744486420/unknown.png
width: 551

**Comment by simsimler** [comment]
𝙅𝙞𝙃𝙮𝙪𝙣: 
On 2021-11-04T17:32:00.792000+00:00

## Attachments
content_type: image/png
filename: unknown.png
height: 380
id: 905872021534175232
proxy_url: https://media.discordapp.net/attachments/773110691624124486/905872021534175232/unknown.png
size: 38255
url: https://cdn.discordapp.com/attachments/773110691624124486/905872021534175232/unknown.png
width: 533

**Comment by simsimler** [comment]
효율적이지 않다 판단되어 닫습니다
